Squashed commit of the following:
commit d57c1e55eb67244df821d806982fd76359892994
Author: Mangosutin <mangostin877@gmail.com>
Date:   Fri Jun 12 00:56:49 2026 +0900

    solveERROR0609

    ERRORの原因は、微分の値が負の値を取っていたために端が微分の値の最大値になっていたこと
    →絶対値をつけよう！
    The cause of the error was that the derivative was taking negative values, causing the boundary to be identified as the maximum value. I will apply an absolute value to fix this.

commit 1553cc2dcff7c110c746ac3a426aeb74f0ff3719
Author: Mangosutin <mangostin877@gmail.com>
Date:   Fri Jun 12 00:53:42 2026 +0900

    sample,grad,diffの折れ線

    9308b6fc2bd5fd29e52ac556d165298a7659e6caから描画プログラムを拝借

commit 42a793c57f4f17713c27d10c99709ae9a6b5642d
Author: fujitenmon-coder <mangostin877@gmail.com>
Date:   Fri Jun 12 00:10:02 2026 +0900

    ERRORの要因はfindexが47(最端)になっていること

commit a5c378d260e11ffe91208082c52e74d8ab253073
Author: fujitenmon-coder <mangostin877@gmail.com>
Date:   Fri Jun 12 00:07:20 2026 +0900

    ignoreに__pycha__を追加

commit 7733459c35e0f217822eeb149dd1e676fbd770cb
Author: fujitenmon-coder <mangostin877@gmail.com>
Date:   Fri Jun 12 00:06:16 2026 +0900

    where_diff_grad_smpleを稼働するようにした。 diffmaxindexの計算の時にerrorが出るので、描画の際はNoneを渡す。

commit e17ae6839ac629bcf392f6590641a2f91501164b
Author: OArikui <Arikui57@outlook.jp>
Date:   Thu Jun 11 20:24:08 2026 +0900

    solveERROR

    line123,129にて、for文中でイテラルオブジェクトを消去していた影響で、以下が発生しました。
    改善しました。

    [Running] python -u "c:\projects\seeing-fork_arikui\ffiinn--sseeiinngg\MIN2_ignore_sunspots.py"
    first circleNone
    only outside circleNone
    �O���̓_�̐�:9,�S�̂̓_�̐�:14
    x,y:(535, 441) min2far:251.75998763759867,y-cyo:50.124474653173934
    x,y:(537, 552) min2far:249.37867741306283,y-cyo:60.875525346826066
    x,y:(594, 662) min2far:191.5648954583974,y-cyo:170.87552534682607
    x,y:(643, 704) min2far:212.86056520432123,x-cxo:143.47799174590307
    x,y:(964, 472) min2far:255.987907534283,y-cyo:19.124474653173934
    Traceback (most recent call last):
      File "c:\projects\seeing-fork_arikui\ffiinn--sseeiinngg\MIN2_ignore_sunspots.py", line 146, in <module>
        print("cx,cy,r=",MIN2_ignore_sunspots(cv2.imread(picpath,0),filter_times=2,show=True,debug=True))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "c:\projects\seeing-fork_arikui\ffiinn--sseeiinngg\MIN2_ignore_sunspots.py", line 115, in MIN2_ignore_sunspots
        x=spots[i][0]
          ~~~~~^^^
    IndexError: list index out of range

commit 73cc7dc89d5c85046d31232ac4cf34f7261561c4
Author: OArikui <Arikui57@outlook.jp>
Date:   Thu Jun 11 20:01:27 2026 +0900

    where_diff_grad_smaleの
    ・sample_libが描画されるように修正
    ・T,Bのwhere_diffのparamを修正

commit 7661520519498993d05109d9ab62c62265a6d372
Author: OArikui <Arikui57@outlook.jp>
Date:   Wed Jun 10 23:13:27 2026 +0900

    整理

commit 18dde2e338133b8b42c26de4dbed5cd528422352
Author: OArikui <Arikui57@outlook.jp>
Date:   Sun Jun 7 10:34:59 2026 +0900

    ERROR

    一回微分の外側で2回微分の最大を探すところでまたERRORが出ました(いつものです)
    ちなむと、NIN2(show=True)は正常でした
    sengiries.pyのwhere_sampleをベースに画像上で何が起きているかを描画する関数を作成し、exceptにいれました。
    例外が発生しました: ValueError
    attempt to get argmax of an empty sequence
      File "C:\Users\fujit\OneDrive\雑多\secfin_seeing_check\ffiinn--sseeiinngg\fin_seeing_allframe.py", line 66, in seeing_one_frame
        realindx=np.argmax(np.diff((samples[fmaxindex:])))+0.5#diffで要素が減る分
                 ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\fujit\OneDrive\雑多\secfin_seeing_check\ffiinn--sseeiinngg\fin_seeing_allframe.py", line 126, in main
        std=seeing_one_frame(readed_img,cir_stat,limb_wigth=24,allp_num=1360,show=False,debug=debug)
      File "C:\Users\fujit\OneDrive\雑多\secfin_seeing_check\ffiinn--sseeiinngg\fin_seeing_allframe.py", line 148, in <module>
        result,Df = main(peadirpath,debug=True)
                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
    ValueError: attempt to get argmax of an empty sequence

commit 7ecd85be395fe3528aedaa1648ee392cc9ea6898
Author: OArikui <Arikui57@outlook.jp>
Date:   Sun Jun 7 09:08:25 2026 +0900

    未検証:一回微分の外側で最大を探すように変更